POST http://localhost:8080/api/reviews/summary

{
  "reviews": ["I recently ordered a laptop and it was in very good condition and it was delivered it on time.
    But there were some software glitches and I couldn't find enough instructions to troubleshoot them.
    Would be great if they provided more detailed manuals.",
    "The smartphone I ordered arrived with a damaged screen. They need to be careful when packaging.",
    "Extrmely satisfied with my orders. Would suggest this place to anyone.",
    "Everything is great about them expect some deliveries take too long.
    Would suggest improving shipping speed to reduce delays."]
}
