POST http://localhost:8080/api/posts/spell-check

{
    "content": "Join us for an exeptional academic experience!
        We are thrilled to host a dynamic conference showcasing the latest research trends
        and groundbreking work in the field. Whether you're an industry profesional, a researcher,
        or an academic enthusiest, this event is not to be missed"
}
